CarpoolingProject/Controllers/TravelController.cs
using CarpoolingProject.Models.RequestModels;
using CarpoolingProject.Services.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarpoolingProject.Web.Controllers
{
    public class TravelController : Controller
    {
        private readonly ITravelService travelService;
        private readonly IUserService userService;
        private readonly IDriverService driverService;

        public TravelController(ITravelService travelService, IUserService userService, IDriverService driverService)
        {
            this.travelService = travelService;
            this.userService = userService;
            this.driverService = driverService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var travels = await travelService.GetAllTravelsAsync();
            return this.View(travels);
        }
        [HttpGet]
        public IActionResult Create()
        {
            var requestModel = new CreateTravelRequestModel();
            return this.View(requestModel);
        }
        [HttpPost]
        public async Task<IActionResult> Create([FromForm] CreateTravelRequestModel requestModel)
        {
            var username = this.HttpContext.Session.GetString("CurrentUser");
            var creator = await userService.GetUsernameAsync(username);
            if (!this.ModelState.IsValid)
            {
                return this.View(requestModel);
            }
            requestModel.CreatorId = creator.UserId;
            await travelService.CreateTravelAsync(requestModel);
            return this.RedirectToAction("Index", "Home");
        }
        [HttpGet]
        public IActionResult Update(int number)
        {
            var requestModel = new UpdateTravelRequestModel();
            requestModel.TravelId = number;
            return this.View(requestModel);
        }
        [HttpPut]
        public async Task<IActionResult> Update([FromForm] UpdateTravelRequestModel requestModel)
        {
            var username = this.HttpContext.Session.GetString("CurrentUser");
            var creator = await userService.GetUsernameAsync(username);
            if (!this.ModelState.IsValid)
            {
                return this.View(requestModel);
            }
            requestModel.CreatorId = creator.UserId;
            await travelService.UpdateTravelAsync(requestModel);
            return this.RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Apply(int number)
        {
            var username = HttpContext.Session.GetString("CurrentUser");
            var passenger = await userService.GetUsernameAsync(username);
            var application = new ApplyForTravelRequestModel();
            application.TravelId = number;
            application.UserId = passenger.UserId;
            await travelService.ApplyForTravel(application);
            return this.RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Sort(string search)
        {
            var travels = await travelService.FilterTravelsByCreator(search);
            return this.View("Index", travels);
        }
        public async Task<IActionResult> GetAllPassengers(int number)
        {
            var requestModel = new GetTravelRequestModel();
            requestModel.TravelId = number;
            var passengers = await driverService.GetAllPassengersForTripAsync(requestModel);
            return this.View("TravelPassengers_TableView", passengers);
        }
        public async Task<IActionResult> GetAllApplicants(int number)
        {
            var requestModel = new GetTravelRequestModel();
            requestModel.TravelId = number;
            var applicants = await travelService.ListApplicantsForTravel(requestModel);
            return this.View("TravelApplications_TableView", applicants);
        }
        //    public async Task<IActionResult> Accept(int number,int applicant)
        //    {
        //        var requestModel = new SelectPassengerRequestModel();
        //        var travel = await travelService.GetTravelAsync(number);
        //        travel
        //    }
        //}
    }
}

CarpoolingProject/Controllers/UserController.cs
using AutoMapper;
using CarpoolingProject.Models.EntityModels;
using CarpoolingProject.Models.RequestModels;
using CarpoolingProject.Services.Interfaces;
using CarpoolingProject.Web.Helper;
using CarpoolingProject.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Authentication;
using System.Threading.Tasks;

namespace CarpoolingProject.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService userService;
        private readonly IMapper mapper;
        private readonly ITravelService travelService;
        private readonly IAuthHelper authHelper;
        private readonly IMailService mailService;

        public UserController(IUserService userService, IMapper mapper, IAuthHelper authHelper, IMailService mailService)
        {
            this.userService = userService;
            this.mapper = mapper;
            this.travelService = travelService;
            this.authHelper = authHelper;
            this.mailService = mailService;
        }

        //GET: /auth/login
        public IActionResult Login()
        {
            var loginViewModel = new LoginViewModel();

            return this.View(loginViewModel);
        }

        //POST: /auth/login
        [HttpPost]
        public async Task<IActionResult> Login([Bind("Username, Password")] LoginViewModel loginViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(loginViewModel);
            }

            try
            {
                var user = await authHelper.TryGetUserAsync(loginViewModel.Username, loginViewModel.Password);
                this.HttpContext.Session.SetString("CurrentUser", user.UserName);
                this.HttpContext.Session.SetString("CurrentRoles", string.Join(',', user.Roles.Select(userRole => userRole.Role.Name)));

                return this.RedirectToAction("index", "home");
            }

            catch (AuthenticationException e)
            {
                this.ModelState.AddModelError("Email", e.Message);
                return this.View(loginViewModel);
            }
        }

        //GET: /auth/logout
        public IActionResult Logout()
        {
            this.HttpContext.Session.Remove("CurrentUser");

            return this.RedirectToAction("index", "home");
        }

        //GET: /auth/register
        public IActionResult Register()
        {
            var registerRequestModel = new CreateUserRequestModel();

            return this.View(registerRequestModel);
        }

        [HttpPost]
        public async Task<IActionResult> Register([FromForm] CreateUserRequestModel requestModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(requestModel);
            }

            if (this.userService.Exist(requestModel.Email))
            {
                this.ModelState.AddModelError("Username", "User with same email already exists.");
                return this.View(requestModel);
            }

            //if (!registerViewModel.Password.Equals(registerViewModel.ConfirmPassword))
            //{
            //    this.ModelState.AddModelError("ConfirmPassword", "Confirm password should match password.");
            //    return this.View(registerViewModel);
            //}          

            await userService.CreateUserAsync(requestModel);
            var userName = requestModel.UserName;
            await mailService.MailVerificationAsync(userName);

            return this.RedirectToAction("Login");
        }

        [HttpPut]
        public async Task<IActionResult> Update(UserViewModel user)
        {
            var userName = HttpContext.Session.GetString("CurrentUser");
            var userToUpdate = await userService.GetUsernameAsync(userName);

            var updateUser = mapper.Map<UpdateUserRequestModel>(user);
            user.UserId = userToUpdate.UserId;

            if (user.ImageFile != null)
            {
                await ExtensionMethod.UploadImageFile(user.UserId, "user", user.ImageFile, false);
                updateUser.ImagePath = $"/images/users/{user.UserId}.jpg";
            }
            await userService.UpdateUserAsync(updateUser);
            return this.View(user);
        }
        public async Task<IActionResult> MyTravels()
        {
            var username = HttpContext.Session.GetString("CurrentUser");
            var user = await userService.GetUsernameAsync(username);

            var travels = await travelService.GetAllTravelsAsync(user.UserId);
            return this.View("MyTravels_TableView", travels);
        }
        public async Task<IActionResult> FutureTravels()
        {
            var username = HttpContext.Session.GetString("CurrentUser");
            var user = await userService.GetUsernameAsync(username);

            var travels = await travelService.FutureTravelsASync(user.UserId);
            return this.View("MyTravels_TableView", travels);
        }
        public async Task<IActionResult> Finish(int id)
        {
            var travel = await travelService.GetTravelAsync(id);
            return RedirectToAction("FutureTravels");
        }

    }
}

CarpoolingProject/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@{
    this.ViewData["IsAuthenticated"] = this.Context.Session.Keys.Contains("CurrentUser");
    this.ViewData["CurrentUser"] = this.Context.Session.Get("CurrentUser");
    this.ViewData["CurrentRoles"] = this.Context.Session.GetString("CurrentRoles");
}
<!DOCTYPE html>
<html lang="en-US" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- ===============================================-->
    <!--    Document Title-->
    <!-- ===============================================-->
    <title>Carpool</title>


    <!-- ===============================================-->
    <!--    Favicons-->
    <!-- ===============================================-->
    <link rel="apple-touch-icon" sizes="180x180" href="~/img/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/img/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/img/favicons/favicon-16x16.png">
    <link rel="shortcut icon" type="image/x-icon" href="~/img/favicons/favicon.ico">
    <link rel="manifest" href="~/img/favicons/manifest.json">
    <meta name="msapplication-TileImage" content="~/img/favicons/mstile-150x150.png">
    <meta name="theme-color" content="#ffffff">


    <!-- ===============================================-->
    <!--    Stylesheets-->
    <!-- ===============================================-->
    <link href="~/vendors/plyr/plyr.css" rel="stylesheet">
    <link href="~/css/theme-rtl.css" rel="stylesheet" />

</head>


<body>

    <!-- ===============================================-->
    <!--    Main Content-->
    <!-- ===============================================-->
    <main class="main" id="top">

        <nav class="navbar navbar-expand-sm fixed-top py-0 backdrop" data-navbar-on-scroll="data-navbar-on-scroll">
            <div class="container">
                <a class="navbar-brand d-flex align-items-center fw-bold fs-2" asp-controller="Home" asp-action="Index"> <img class="d-inline-block align-top img-fluid" src="assets/img/gallery/logo-icon.png" alt="" width="50" /><span class="text-primary fs-4 ps-2">Carpool</span></a>
                <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

                <div class="collapse navbar-collapse border-top border-lg-0 mt-4 mt-lg-0" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto pt-2 pt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-600" href="#featuresVideos">Video</a>
                        </li>
                        <li class="nav-link active">
                            <a asp-controller="Travel" asp-action="Index">Travels</a>
                        </li>

                    </ul>
                    @if (!(bool)this.ViewData["isAuthenticated"])
                    {

                        <form class="ps-lg-5">
                            <a class="btn btn-lg btn-outline-primary order-0" asp-controller="User" asp-action="Login">Sign In</a>
                        </form>
                    }
                    else
                    {
                        <div class="dropdown">
                            <a data-bs-toggle="dropdown" id="dropDownUser1">
                                <img class="rounded-circle" src="~/img/icons/1200px-Circle-icons-profile.svg.png" alt="Submit" width="48" height="48">
                                
                            </a>
                            <ul class="dropdown-menu text-small" aria-labelledby="dropDownUser1">
                                <li>
                                    <a class="dropdown-item" asp-controller="User" asp-action="MyTravels">My Travels</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-controller="User" asp-action="">My Travels</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-controller="User" asp-action="FutureTravels">Ongoing Travels</a>
                                </li>
                                
                            </ul>  
                        </div>
                        <form>
                            <a asp-controller="User" asp-action="Logut"></a>
                        </form>
                        <a class="btn btn-lg btn-outline-primary order-0" asp-controller="User" asp-action="Logout">Sign out</a>
                    }

                </div>

            </div>
        </nav>



        <!-- ============================================-->

        @RenderBody()
    </main>
    <!-- ===============================================-->
    <!--    End of Main Content-->
    <!-- ===============================================-->
    <!-- ===============================================-->
    <!--    JavaScripts-->
    <!-- ===============================================-->
    <script src="~/vendors/_popperjs/popper.min.js"></script>
    <script src="~/vendors/bootstrap/bootstrap.min.js"></script>
    <script src="~/vendors/is/is.min.js"></script>
    <script src="~/vendors/plyr/plyr.polyfilled.min.js"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
    <script src="~/js/theme.js"></script>

    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200;300;400;600;700;800;900&amp;display=swap" rel="stylesheet">
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>